from typing import Iterator

from chat.chat_util import present_results
from chat.conversation import Conversation, AiMessage, Message
from chat.tools.tool import Tool
from nlp.agent import Agent


class AskAnExpert(Tool):
    schema = {
        "name": "ask_an_expert",
        "description": "If none of the other tools satisfy the user's request, ask an expert for help."
    }
    verbal_return_type = "an answer generated by GPT-4o"

    def call(self, agent: Agent, request: str, history=Conversation([]), state=None) -> Iterator[Message]:
        """
        Asks the LLM to answer the user's prompt directly.
        """
        yield present_results(agent, history, self.verbal_return_type)
        yield ask_llm_for_expert_opinion(agent, history)


def ask_llm_for_expert_opinion(agent: Agent, conversation: Conversation):
    """
    Asks the LLM to answer the user's prompt directly.
    """
    result = agent.client.chat.completions.create(
        model="gpt-4o",
        temperature=1,
        response_model=None,
        messages=conversation.render_to_openai("You are a biodiversity expert.")
    )

    return AiMessage(result.choices[0].message.content)
